name: Cypress Tests
on:
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate Test Run ID
        id: test-run-id
        run: echo "::set-output name=id::$(npx uuid)"

      - name: Run Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: Replay Firefox
        env:
          CYPRESS_BASE_URL: https://www.replayable.dev/
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
          RECORD_REPLAY_TEST_RUN_ID: ${{ steps.test-run-id.outputs.id }}

      - name: List Replays
        run: npx @replayio/replay ls --json

      - name: Upload Replays
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: ${{ secrets.CYPRESS_REPLAY_API_KEY }}
