name: Playwright Tests
on: 
  deployment_status:  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Get PR Number
        uses: actions/github-script@v6
        id: pr-number
        with:
          result-encoding: json
          script: |
            try {
              const results = await github.rest.search.issuesAndPullRequests({
                q: context.sha
              });
              const prs = [...results.data.items].sort((a, b) => a.score - b.score);
              if (prs[0]) {
                return prs[0].number;
              }
            } catch (e) {
              console.error(e);
            }

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        uses: replayio/action-playwright@v0.4.10
        with:
          project: firefox
          issue-number: ${{ steps.pr-number.outputs.result }}
          apiKey: ${{ secrets.REPLAYWORKSPACEAPIKEY }}
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
